### ISSUE TITLE
No module named build

### ISSUE THREAD

**Issue by BadCo-NZ** [bpetrikovics/shelly-ota#2]
Good evening!

Just went through updating all my things, and see you put out a new update, nice work!

I followed through the reademe and all went fine, until I tried to build the python package to install outside of the virtualenv.

``` bash
(venv) root@shelly-ota:~/shelly-ota# python3 -m build
/root/shelly-ota/venv/bin/python3: No module named build
```

I am not a developer so I may be doing something basic wrong.

Thanks

**Comment by bpetrikovics** [comment]
Hi,

Looks like another sloppy job on my side regarding documentation, sorry about that. In my environment, I have the "build" python package but yours does not have. Not an issue, can be installed with

```bash
python3 -m pip install build
```

Afterwards the build should succeed. Hope this works for you, I'll fix (again) the documentation.

**Comment by BadCo-NZ** [comment]
No worries, I'll check this tonight and report back.

If you do another release, hit me up if you want a tester 😅

**Comment by bpetrikovics** [comment]
Sure. There might be an update soon for supporting password-protected devices.

**Comment by BadCo-NZ** [comment]
Ok so installed the build module as you mentioned. It still failed...

```bash
(venv) root@shelly-ota:~/shelly-ota# python3 -m build
* Creating venv isolated environment...
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/build-env-equehyxt/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

So I installed python3.10-venv

```bash
(venv) root@shelly-ota:~/shelly-ota# apt install python3.10-venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  python3.10-venv
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 5718 B of archives.
After this operation, 28.7 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3.10-venv amd64 3.10.6-1~22.04 [5718 B]
Fetched 5718 B in 1s (6735 B/s)                       
Selecting previously unselected package python3.10-venv.
(Reading database ... 27958 files and directories currently installed.)
Preparing to unpack .../python3.10-venv_3.10.6-1~22.04_amd64.deb ...
Unpacking python3.10-venv (3.10.6-1~22.04) ...
Setting up python3.10-venv (3.10.6-1~22.04) ...
```

Then re-ran the build:
```
(venv) root@shelly-ota:~/shelly-ota# python3 -m build
...
Successfully built shelly-ota-2022.8.20.tar.gz and shelly_ota-2022.8.20-py3-none-any.whl
```

Then I continued with the instructions:
```bash
(venv) root@shelly-ota:~/shelly-ota# pip install dist/shelly-ota*tar.gz
Processing ./dist/shelly-ota-2022.8.20.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: netifaces in ./venv/lib/python3.10/site-packages (from shelly-ota==2022.8.20) (0.11.0)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from shelly-ota==2022.8.20) (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->shelly-ota==2022.8.20) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in ./venv/lib/python3.10/site-packages (from requests->shelly-ota==2022.8.20) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->shelly-ota==2022.8.20) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->shelly-ota==2022.8.20) (3.4)
Building wheels for collected packages: shelly-ota
  Building wheel for shelly-ota (pyproject.toml) ... done
  Created wheel for shelly-ota: filename=shelly_ota-2022.8.20-py3-none-any.whl size=6135 sha256=1073dfe7a3d1c57e6bcdcae19c83c47ac572d0cfecc5515e306ce709fe35f970
  Stored in directory: /root/.cache/pip/wheels/e7/85/b5/7755b421eb73d71a0f877a92aa3be0975e4f88c990c4386d1d
Successfully built shelly-ota
Installing collected packages: shelly-ota
  Attempting uninstall: shelly-ota
    Found existing installation: shelly-ota 2022.8.20
    Uninstalling shelly-ota-2022.8.20:
      Successfully uninstalled shelly-ota-2022.8.20
Successfully installed shelly-ota-2022.8.20
```

But now i am not sure of the next step, how do I run `shelly-ota` without the virtualenv?

**Comment by bpetrikovics** [comment]
You can either a.) run the whole build and install outside a virtualenv or b.) you can exit the virtualenv after you've built the package, by using the "deactivate" command, and then using pip install to install the freshly created package outside your virtualenv.

Option c.) is if I build and upload a pre-built package to this repo. I will probably just do that.

**Comment by BadCo-NZ** [comment]
> You can either a.) run the whole build and install outside a virtualenv or b.) you can exit the virtualenv after you've built the package, by using the "deactivate" command, and then using pip install to install the freshly created package outside your virtualenv.
> 
> Option c.) is if I build and upload a pre-built package to this repo. I will probably just do that.

Thanks, I managed to muddle my way through the rest of it.

For the sake of others, as mentioned by @bpetrikovics:

1. Exit the virtualenc with 
  `(venv) root@shelly-ota:~/shelly-ota# deactivate`
3. Move to the directory with the package 
  `root@shelly-ota:~/shelly-ota# cd dist/`
5. Install the package 
  `root@shelly-ota:~/shelly-ota/dist# pip install shelly-ota-2022.8.20.tar.gz`
7. Profit!

Thanks @bpetrikovics for answering what are probably basic questions to a developer :)
