### ISSUE TITLE
Implement 'Restrict Login' Support

### ISSUE THREAD

**Issue by BadCo-NZ** [bpetrikovics/shelly-ota#5]
As discussed in #3 , this is a feature request for implementing the ability to work with Shellys built in basic user authentication.

**Comment by BadCo-NZ** [comment]
I am happy to assist in any testing

**Comment by bpetrikovics** [comment]
Working on that already in the https://github.com/bpetrikovics/shelly-ota/tree/device-auth branch, just don't have any devices around with outdated firmware, so at this point it's more or less a thought experiment :) Feel free to give it a try.

**Comment by BadCo-NZ** [comment]
> Working on that already in the https://github.com/bpetrikovics/shelly-ota/tree/device-auth branch, just don't have any devices around with outdated firmware, so at this point it's more or less a thought experiment :) Feel free to give it a try.

Yeah I saw that PR after I posted, oops 😅 I will give it a try tonight.

Alternatively you can roll back a firmware:
https://sequr.be/blog/2020/11/force-update/downgrade-shelly-firmware/

**Comment by bpetrikovics** [comment]
Let me know if you had any luck - I realize I did not really add any instructions around how to use/build the branch, so if you had trouble trying it out maybe I can help. Otherwise maybe I can do some testing on my own as I will probably have a few new devices around.

**Comment by bpetrikovics** [comment]
Tested with password in environment. Documentation will follow in a bit.

**Comment by BadCo-NZ** [comment]
Nice work, you beat me to it 😅 hopefully I will be able to test it this weekend.
