### ISSUE TITLE
Provide pre-built package for easier installation.

### ISSUE THREAD

**Issue by BadCo-NZ** [bpetrikovics/shelly-ota#6]
As discussed in #2 this is a feature request to supply a pre-built package for easier installation for less developer focused users :)

**Comment by BadCo-NZ** [comment]
I am happy to assist in any testing

**Comment by bpetrikovics** [comment]
Package is now provided in the release, in wheel (.whl) format, installable with pip directly.

**Comment by BadCo-NZ** [comment]
Nice work, hopefully I'll have time to test this weekend.
